function names = required_signal_names()
%REQUIRED_SIGNAL_NAMES Canonical logged-output contract.
names={"irradiance","temperature","pv_voltage","pv_current","pv_power","theoretical_mpp_power", ...
"mppt_duty","converter_input_current","dc_bus_voltage","dc_bus_current","surge_injected", ...
"spd_voltage","spd_current","sc_voltage","sc_current","sc_converter_current","sc_power", ...
"relay_command","relay_state","controller_state","overvoltage_timer","warning_flag","emergency_flag", ...
"automatic_reset_flag","manual_reset","downstream_voltage","downstream_current","downstream_power", ...
"sc_converter_enabled","spd_demanded_current","spd_saturation_flag","spd_saturation_duration", ...
"spd_cumulative_energy","spd_overstress_state","sc_internal_voltage","sc_terminal_voltage", ...
"sc_current_command_raw","sc_current_command","sc_actual_current","sc_esr_voltage","sc_esr_power", ...
"sc_esr_energy","sc_current_limit_flag","sc_current_limit_duration","sc_overvoltage_flag", ...
"sc_undervoltage_flag","threshold_crossing_time","trip_command_time","relay_opening_time", ...
"safe_interval_start_time","reconnect_command_time","relay_closing_time","protection_armed", ...
"safe_interval_interruption_count","inverter_requested_power","inverter_uvlo", ...
"inverter_overvoltage_shutdown","inverter_soft_start","inverter_dc_input_power"};
end
