function comparison = verify_simscape_against_coded
%VERIFY_SIMSCAPE_AGAINST_CODED Compare the physical and coded T05 models.

root = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(root));
P = project_parameters;
scenarios = test_scenarios(P);
scenario = scenarios(find(string({scenarios.Test_ID}) == "T05",1));

coded = run_single_scenario(scenario,P, ...
    fullfile(root,'model','PV_Lightning_Protection.slx'));
physical = runPhysicalModel(root,P,scenario);

eventStart = scenario.Event_Start;
eventEnd = scenario.Event_End;
preStart = eventStart - 0.03;
codedTime = coded.signals.time(:);
codedPre = codedTime >= preStart & codedTime < eventStart;
codedEvent = codedTime >= eventStart & codedTime <= eventEnd;

pvVoltage = physical.get('Simscape_pv_voltage');
pvCurrent = physical.get('Simscape_pv_current');
busVoltage = physical.get('Simscape_bus_voltage');
spd1Current = physical.get('Simscape_spd_current');
spd2Current = physical.get('Simscape_spd2_current');
scVoltage = physical.get('Simscape_sc_voltage');
scCurrent = physical.get('Simscape_sc_current');
acVoltage = physical.get('Simscape_ac_voltage');
acCurrent = physical.get('Simscape_ac_current');

physicalPre = busVoltage.Time >= preStart & busVoltage.Time < eventStart;
physicalEvent = busVoltage.Time >= eventStart & busVoltage.Time <= eventEnd;
acPre = acVoltage.Time >= preStart & acVoltage.Time < eventStart;

metric = [ ...
    "PV voltage before event (V)"; ...
    "PV current before event (A)"; ...
    "PV power before event (W)"; ...
    "DC bus before event (V)"; ...
    "Peak protected DC bus (V)"; ...
    "Peak aggregate SPD current (A)"; ...
    "Peak supercapacitor voltage (V)"; ...
    "Peak supercapacitor current (A)"; ...
    "Load power before event (W)"];

codedValue = [ ...
    mean(coded.signals.pv_voltage.Data(codedPre)); ...
    mean(coded.signals.pv_current.Data(codedPre)); ...
    mean(coded.signals.pv_power.Data(codedPre)); ...
    mean(coded.signals.dc_bus_voltage.Data(codedPre)); ...
    max(coded.signals.dc_bus_voltage.Data(codedEvent)); ...
    max(abs(coded.signals.spd_current.Data(codedEvent))); ...
    max(coded.signals.sc_voltage.Data(codedEvent)); ...
    max(abs(coded.signals.sc_current.Data(codedEvent))); ...
    mean(coded.signals.downstream_power.Data(codedPre))];

physicalValue = [ ...
    mean(pvVoltage.Data(physicalPre)); ...
    mean(pvCurrent.Data(physicalPre)); ...
    mean(pvVoltage.Data(physicalPre).*pvCurrent.Data(physicalPre)); ...
    mean(busVoltage.Data(physicalPre)); ...
    max(busVoltage.Data(physicalEvent)); ...
    max(abs(spd1Current.Data(physicalEvent) + spd2Current.Data(physicalEvent))); ...
    max(scVoltage.Data(physicalEvent)); ...
    max(abs(scCurrent.Data(physicalEvent))); ...
    mean(acVoltage.Data(acPre).*acCurrent.Data(acPre))];

tolerancePercent = [8; 10; 8; 8; 5; 5; 3; 3; 8];
errorPercent = 100*(physicalValue-codedValue)./max(abs(codedValue),eps);
status = repmat("PASS",size(metric));
status(abs(errorPercent) > tolerancePercent) = "FAIL";
comparison = table(metric,codedValue,physicalValue,errorPercent, ...
    tolerancePercent,status);

[codedTrip,physicalTrip] = fallingEdgeTimes( ...
    coded.signals.relay_command,codedTime, ...
    physical.get('Simscape_relay_command'));
[codedOpen,physicalOpen] = fallingEdgeTimes( ...
    coded.signals.relay_state,codedTime, ...
    physical.get('Simscape_relay_state'));
[codedReconnect,physicalReconnect] = risingEdgeTimesAfter( ...
    coded.signals.relay_command,codedTime, ...
    physical.get('Simscape_relay_command'),eventEnd);

timingMetric = ["Trip command time (s)"; "Relay opening time (s)"; ...
    "Reconnect command time (s)"];
codedTiming = [codedTrip; codedOpen; codedReconnect];
physicalTiming = [physicalTrip; physicalOpen; physicalReconnect];
toleranceSeconds = [0.005; 0.005; 0.030];
absoluteErrorSeconds = abs(physicalTiming-codedTiming);
timingStatus = repmat("PASS",size(timingMetric));
timingStatus(absoluteErrorSeconds > toleranceSeconds) = "FAIL";
timingComparison = table(timingMetric,codedTiming,physicalTiming, ...
    absoluteErrorSeconds,toleranceSeconds,timingStatus);

disp(comparison);
disp(timingComparison);
assert(all(comparison.status == "PASS") && all(timingComparison.timingStatus == "PASS"), ...
    'Simscape-to-coded comparison exceeded one or more calibration tolerances.');
end

function output = runPhysicalModel(root,P,scenario)
scenarioInput = configure_scenario(scenario,P);
modelName = 'PV_Lightning_Protection_Simscape';
load_system(fullfile(root,'model',[modelName '.slx']));
modelWorkspace = get_param(modelName,'ModelWorkspace');
assignin(modelWorkspace,'P',P);
assignin(modelWorkspace,'scenario_input',scenarioInput);
input = Simulink.SimulationInput(modelName);
input = input.setVariable('P',P).setVariable('scenario_input',scenarioInput);
input = input.setModelParameter('StopTime',num2str(scenario.StopTime), ...
    'ReturnWorkspaceOutputs','on');
output = sim(input);
close_system(modelName,0);
end

function [codedTime,physicalTime] = fallingEdgeTimes(codedSignal,time,physicalSignal)
codedIndex = find(diff(codedSignal.Data) < -0.5,1);
physicalIndex = find(diff(physicalSignal.Data) < -0.5,1);
codedTime = time(codedIndex+1);
physicalTime = physicalSignal.Time(physicalIndex+1);
end

function [codedTime,physicalTime] = risingEdgeTimesAfter( ...
    codedSignal,time,physicalSignal,afterTime)
codedIndex = find(diff(codedSignal.Data) > 0.5 & time(2:end) > afterTime,1);
physicalIndex = find(diff(physicalSignal.Data) > 0.5 & ...
    physicalSignal.Time(2:end) > afterTime,1);
codedTime = time(codedIndex+1);
physicalTime = physicalSignal.Time(physicalIndex+1);
end
