function results = verify_simscape_simplified_structure()
%VERIFY_SIMSCAPE_SIMPLIFIED_STRUCTURE Check the professor-facing hierarchy.

root = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(root));
modelName = 'PV_Lightning_Protection_Simscape';
modelPath = fullfile(root,'model',[modelName '.slx']);
load_system(modelPath);
cleanup = onCleanup(@()close_system(modelName,0));

expectedTopLevel = sort({ ...
    '01 INPUTS - PV MPPT & BOOST CONTROL'; ...
    '02 LIGHTNING COMMAND'; ...
    '03A PV ARRAY'; ...
    '03B SURGE SOURCE & CABLE'; ...
    '03C SPD1 PRIMARY PROTECTION'; ...
    '03D SPD2 COORDINATED PROTECTION'; ...
    '03E PROTECTED DC BUS'; ...
    '03F SUPERCAPACITOR BANK'; ...
    '03G RELAY & DC LOAD'; ...
    '03H INVERTER & AC LOAD'; ...
    '05 SUPERCAP CONTROL'; ...
    '06 RELAY PROTECTION CONTROL'; ...
    '07 INVERTER CONTROL'; ...
    '08 RESULTS - SCOPES & LOGGING'; ...
    'DERIVED METRICS'; ...
    'USER SETTINGS - DOUBLE CLICK'});
topBlocks = find_system(modelName,'SearchDepth',1,'Type','Block');
topBlocks = topBlocks(~strcmp(topBlocks,modelName));
actualTopLevel = sort(cellfun(@(path)get_param(path,'Name'), ...
    topBlocks,'UniformOutput',false));
assert(isequal(actualTopLevel,expectedTopLevel), ...
    'The simplified top-level workflow has changed.');

stageNames = { ...
    '03A PV ARRAY','03B SURGE SOURCE & CABLE', ...
    '03C SPD1 PRIMARY PROTECTION','03D SPD2 COORDINATED PROTECTION', ...
    '03E PROTECTED DC BUS','03F SUPERCAPACITOR BANK', ...
    '03G RELAY & DC LOAD','03H INVERTER & AC LOAD'};
referenceCount = 0;
connectedCommands = 0;
for stageIndex = 1:numel(stageNames)
    stage = [modelName '/' stageNames{stageIndex}];
    stageBlocks = find_system(stage,'SearchDepth',1,'Type','Block');
    for blockIndex = 1:numel(stageBlocks)
        try
            reference = get_param(stageBlocks{blockIndex},'ReferenceBlock');
        catch
            reference = '';
        end
        referenceCount = referenceCount + ~isempty(reference);
    end
    stagePorts = get_param(stage,'PortHandles');
    connectedCommands = connectedCommands + sum(arrayfun(@(port) ...
        hasValidSource(port),stagePorts.Inport));
    assert(isempty(stagePorts.Outport), ...
        '%s contains an unnecessary top-level output.',stageNames{stageIndex});
end
assert(referenceCount == 76, ...
    'Expected 76 physical/library blocks across the eight electrical stages.');

resultsPath = [modelName '/08 RESULTS - SCOPES & LOGGING'];
scopeCount = numel(find_system(resultsPath,'SearchDepth',1, ...
    'BlockType','Scope'));
loggerCount = numel(find_system(resultsPath,'SearchDepth',1, ...
    'BlockType','ToWorkspace'));
assert(scopeCount == 8,'Expected eight ordered Scope blocks.');
assert(loggerCount == 22,'Expected all 22 verification loggers.');

assert(connectedCommands == 7, ...
    'Expected seven labeled command inputs across the electrical stages.');

% No Mux/Demux port or ordinary Simulink signal may end in an open stub.
routingBlocks = [find_system(modelName,'FollowLinks','off', ...
    'LookUnderMasks','all','BlockType','Mux'); ...
    find_system(modelName,'FollowLinks','off', ...
    'LookUnderMasks','all','BlockType','Demux')];
for blockIndex = 1:numel(routingBlocks)
    ports = get_param(routingBlocks{blockIndex},'PortHandles');
    assert(all(arrayfun(@hasValidSource,ports.Inport)), ...
        'Unused Mux input found in %s.',routingBlocks{blockIndex});
    assert(all(arrayfun(@hasValidDestination,ports.Outport)), ...
        'Unused Demux output found in %s.',routingBlocks{blockIndex});
end

systems = [{modelName}; find_system(modelName,'FollowLinks','off', ...
    'LookUnderMasks','all','BlockType','SubSystem')];
for systemIndex = 1:numel(systems)
    lines = find_system(systems{systemIndex},'SearchDepth',1, ...
        'FindAll','on','Type','line');
    for lineIndex = 1:numel(lines)
        source = get_param(lines(lineIndex),'SrcPortHandle');
        if ~isempty(source) && source > 0 && ...
                strcmp(get_param(source,'PortType'),'outport')
            destinations = get_param(lines(lineIndex),'DstPortHandle');
            assert(any(destinations > 0), ...
                'Dangling Simulink branch found in %s.',systems{systemIndex});
        end
    end
end

set_param(modelName,'SimulationCommand','update');
results = table(numel(topBlocks),referenceCount,connectedCommands, ...
    scopeCount,loggerCount,'VariableNames', ...
    {'TopLevelBlocks','PhysicalLibraryBlocks','VisibleCommandPaths', ...
    'Scopes','WorkspaceLoggers'});
disp(results);
end

function connected = hasValidSource(portHandle)
lineHandle = get_param(portHandle,'Line');
connected = false;
if lineHandle > 0
    source = get_param(lineHandle,'SrcPortHandle');
    connected = ~isempty(source) && source > 0;
end
end

function connected = hasValidDestination(portHandle)
lineHandle = get_param(portHandle,'Line');
connected = false;
if lineHandle > 0
    destinations = get_param(lineHandle,'DstPortHandle');
    connected = any(destinations > 0);
end
end
